### ISSUE TITLE
How to reuse jobs, parameters across multiple workflow config files

### ISSUE THREAD

**Issue by kp-abhishek-agrawal** [bufferings/orb-split-config#13]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the problem imposed by not having this feature

I have few jobs, commands & parameters which are shared across multiple workflow files. Is there any way where I can reuse them? Currently, it throws an error if same job or parameter is not found within same workflow config?

### Describe the solution you'd like

Lot of duplicate code for executers, parameters & jobs which can be resused across multiple workflows

**Comment by bufferings** [comment]
@kp-abhishek-agrawal Thank you for asking!
I understood you want to define common executors, jobs, and parameters in one place and reuse them in the workflows.
You can do that.

I created an example project for your reference.
https://github.com/bufferings/orb-split-config-example-for-reuse

You can define common items like this (https://github.com/bufferings/orb-split-config-example-for-reuse/blob/main/common/.circleci/config.yml)
```yaml
parameters:
  common-my-name:
    type: string
    default: "World"

executors:
  common-executor:
    docker:
      - image: cimg/base:stable

jobs:
  common-say-hello:
    executor: common-executor
    environment:
      MY_NAME: << pipeline.parameters.common-my-name >>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, ${MY_NAME}! common"
```

and you can use them from each file like this (https://github.com/bufferings/orb-split-config-example-for-reuse/blob/main/service1/.circleci/config.yml):

```yaml
version: 2.1

jobs:
  service1-say-hello:
    executor: common-executor
    environment:
      MY_NAME: << pipeline.parameters.common-my-name >>
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, ${MY_NAME}!1"

workflows:
  service1-say-hello-workflow:
    jobs:
      - common-say-hello
      - service1-say-hello
```

Does this answer your question?
